### ISSUE TITLE
How to use the swenv component in lualine?

### ISSUE THREAD

**Issue by desilinguist** [AckslD/swenv.nvim#11]
Sorry, I am new to neovim so it's not obvious to me how to use the lualine component provided by this plugin? It'd be great if this was in the documentation too.

**Comment by desilinguist** [comment]
Never mind. It works.

**Comment by AckslD** [comment]
Happy to hear it worked! :) If you have a snippet you think would be useful for others. Feel free to open a PR to add it to the README.

**Comment by skolj** [comment]
hey! does the icon work though? I use a jetbrains nerd font and it doesn't seem to render the icon. Is it possible to change the icon through config?

**Comment by AckslD** [comment]
@skolj, I see I didn't expose any configuration for this but could easily be done. Is that something you would like contribute with :)

**Comment by skolj** [comment]
Sure, I'd be happy to help! However, it looks like I can use the default `icon` component option and customize it. But the hardcoded icon and highlight from the swenv component are still there. 

This line in my config
<img width="1100" alt="image" src="https://github.com/AckslD/swenv.nvim/assets/41965293/973ed324-7734-4d77-9300-f205b021b9f2">

gives me this result. 
<img width="137" alt="image" src="https://github.com/AckslD/swenv.nvim/assets/41965293/cc35c931-bac5-4e9b-ab0c-a23d023e3385">

Do you need help with any changes?

**Comment by AckslD** [comment]
Maybe the lualine plugin should be restructured, I honestly wasn't fully sure how it should look like so I put the icon directly in the string returned from `update_status`:
https://github.com/AckslD/swenv.nvim/blob/adaa088121d2716611cad814ecc8f0cf73d0cc57/lua/lualine/components/swenv.lua#L19

Maybe only the venv name should be returned and icons etc go into `self.options` in `init`? Any thoughts on this?

**Comment by skolj** [comment]
yeah, that'd be nice I guess. I could move the hardcoded icon to default `icon` option. Also, do we really need a default highlight?

**Comment by AckslD** [comment]
Sounds good @skolj, yeah maybe default highlight is not needed indeed and the user can set that instead

**Comment by skolj** [comment]
Created a [PR](https://github.com/AckslD/swenv.nvim/pull/13) as discussed :) let me know if anything needs updating.

**Comment by DanielAndreasen** [comment]
Thanks both to the work on the icon stuff. Can one of you help me the last bit? I prefer no icon. Here is my `sections` part from the `lualine` config:

```lua
  sections = {
    lualine_a = {'mode'},
    lualine_b = {'branch', 'diff', 'swenv', icon=''},
    lualine_c = {'filename'},
    lualine_x = {'filetype'},
    lualine_y = {'searchcount'},
    lualine_z = {'progress'}
  },
```
But that does not work.

**Comment by skolj** [comment]
@DanielAndreasen wrap `swenv` component in braces, i.e., `lualine_b = {'branch', 'diff', { 'swenv', icon='' } },`

**Comment by DanielAndreasen** [comment]
Perfect - thanks for the reply. Works like a charm
