### ISSUE TITLE
Initially setting the venv to the terminal's venv on startup 

### ISSUE THREAD

**Issue by serhez** [AckslD/swenv.nvim#12]
Hello!

Could it be possible to initially set the venv to the one which is already activated on the terminal initially on nvim's startup (i.e., when calling swenv's `setup()`)?

Thanks!

**Comment by AckslD** [comment]
Isn't that already activated? Ie if you open `:term` and run python? Or do you mean that it's not shown in the status bar which is indeed true.

**Comment by skolj** [comment]
hey! created a [PR](https://github.com/AckslD/swenv.nvim/pull/14) that solves this. Let me know if that looks ok.
