### ISSUE TITLE
Unable to detect the packages from the virtual environment present in current directory .

### ISSUE THREAD

**Issue by akashdiphazra** [AckslD/swenv.nvim#15]
I have created a virtual environment named myenv in the current directory, swenv detects the virtual environment but unable to detect packages present in it.

``` lua 

require('swenv').setup({
  -- Should return a list of tables with a `name` and a `path` entry each.
  -- Gets the argument `venvs_path` set below.
  -- By default just lists the entries in `venvs_path`.
  get_venvs = function(venvs_path)
    return require('swenv.api').get_venvs(venvs_path)
  end,
  -- Path passed to `get_venvs`.
  venvs_path = vim.fn.expand('.'),
  -- Something to do after setting an environment, for example call vim.cmd.LspRestart
  post_set_venv = nil,
})

````

https://github.com/AckslD/swenv.nvim/assets/61003681/96d49c62-e872-442c-b014-48a89f3b4b56

**Comment by AckslD** [comment]
Does it work if you do `:LspRestart` after switching venv?

**Comment by akashdiphazra** [comment]
No it, still doesn't works

[Screencast from 2023-06-02 19-49-39.webm](https://github.com/AckslD/swenv.nvim/assets/61003681/b90b5eb3-f41e-4be2-ad05-6af827af527b)

**Comment by skolj** [comment]
@akashdiphazra I believe the problem is with `vim.fn.expand('.')` when you set `venvs_path`. It doesn't get expanded to the correct absolute path. You might wanna change it to `venvs_path = vim.fn.getcwd()` instead and then give it a try.

**Comment by akashdiphazra** [comment]
I not proficient with lua api's in neovim. It worked thanks @skolj
