### ISSUE TITLE
Omit "base" from lualine

### ISSUE THREAD

**Issue by aemonge** [AckslD/swenv.nvim#21]
Can we have an option that when the "base" env is selected, don't display anything on the lualine ?

**Comment by AckslD** [comment]
We could have some custom filter for when to display or not but I'm not sure I see the reason for this?

**Comment by aemonge** [comment]
The main reason, would be when you're editing a none python document, such as a pure front-end workspace. In this case, your python environment is meaningless.

**Comment by AckslD** [comment]
That seems different though than not displaying it for a given "base" venv. Ie instead you want to only display when `ft=python`? Although the python venv can still affect non-python files depending on what executables you're relying on. But that can be maybe exposed as an option indeed.

**Comment by AckslD** [comment]
That seems different though than not displaying it for a given "base" venv. Ie instead you want to only display when `ft=python`? Although the python venv can still affect non-python files depending on what executables you're relying on. But that can be maybe exposed as an option indeed.

**Comment by aemonge** [comment]
Yeah, `ft=python` would work :)

Yeah, as long as it's the `base` env you should be aware of your global libs applied in other `ft`s .

Ideally, would be nice to have `nodenv` inside a conda env; but that's defenetelly out of scope.

**Comment by skolj** [comment]
You can add `cond` to your lualine config and only show the lualine component in python files. Something like this:
``` 
lualine_x = {
  {
    "swenv",
    cond = function()
      return vim.bo.filetype == "python"
    end
  },
}

```
@aemonge Is that what you were looking for?

**Comment by AckslD** [comment]
Thanks @skolj!

**Comment by aemonge** [comment]
Thanks @skolj !
