### ISSUE TITLE
error occur

### ISSUE THREAD

**Issue by JINNMnm** [AckslD/swenv.nvim#24]
after installing it, when i call
:lua require("swenv.api").pick_venv()
and it shows:
E5108: Error executing lua vim/shared.lua:0: src: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua: in function 'validate'
        vim/shared.lua: in function 'list_extend'
        ...nvim/site/pack/packer/start/swenv.nvim/lua/swenv/api.lua:124: in function 'get_venvs'
        ...nvim/site/pack/packer/start/swenv.nvim/lua/swenv/api.lua:132: in function 'pick_venv'
        [string ":lua"]:1: in main chunk

**Comment by ikkihou** [comment]
same error as u
<img width="1675" alt="image" src="https://github.com/AckslD/swenv.nvim/assets/51254965/07c11a35-1eff-4d01-9efe-bfab40745d86">

**Comment by Adictya** [comment]
It's happening cuz of a missing return statement after https://github.com/AckslD/swenv.nvim/blob/a85fc11dbf1bf0fa4aa3b683443957e8789da5e5/lua/swenv/api.lua#L101 , added it locally which fixes it, seems like small miss, should only be a matter of time before the authors fix it.

**Comment by ikkihou** [comment]
Excellent👍, thanks for ur suggestion! The bug fixed

**Comment by JINNMnm** [comment]
thx bro!
Bug fixed

**Comment by JINNMnm** [comment]
thx bro! 
Bug fixed!

**Comment by AckslD** [comment]
sorry my bad, should be fixed now
