### ISSUE TITLE
Didnt work for me with airline plugin :(

### ISSUE THREAD

**Issue by JINNMnm** [AckslD/swenv.nvim#26]
After i pick a new env by calling"pick_venv()"
My airline plugin still not change to the selected env.
<img width="1507" alt="image" src="https://github.com/AckslD/swenv.nvim/assets/126888564/1c9e29f5-52c4-4b43-86ac-03ac7ff55372">

**Comment by AckslD** [comment]
Impossible to know what's wrong without any more information
