### ISSUE TITLE
Conda support?

### ISSUE THREAD

**Issue by lkhphuc** [AckslD/swenv.nvim#3]
Would be great to have conda support. I'm trying to use this with neovide since neovide doesn't pickup the python env when it started up.

**Comment by AckslD** [comment]
Sounds good @lkhphuc! I don't use conda so probably won't implement this myself but it you or anyone else would like to feel free to open a PR.

**Comment by AckslD** [comment]
Sounds good @lkhphuc! I don't use conda so probably won't implement this myself but it you or anyone else would like to feel free to open a PR.

**Comment by ChristianChiarulli** [comment]
not sure if you're still looking for conda support @AckslD but if you are you can try out this PR: https://github.com/AckslD/swenv.nvim/pull/6

**Comment by meicale** [comment]
I cannot change the conda env. I can list and pic all the conda env, but it doesn't works. I can not you the "require('swenv.api').get_current_venv()" which return nothing. But I tried ":!which python" it give me the right python path in conda env. That is wired. I just modify the envs_path = vim.fn.expand('~/anaconda/envs'). Did I do anything wrong?
CondaChangeEnv command from other plugin works.

**Comment by AckslD** [comment]
Is it working for you @ChristianChiarulli ?

**Comment by skolj** [comment]
> I cannot change the conda env. I can list and pic all the conda env, but it doesn't works. I can not you the "require('swenv.api').get_current_venv()" which return nothing. But I tried ":!which python" it give me the right python path in conda env. That is wired. I just modify the envs_path = vim.fn.expand('~/anaconda/envs'). Did I do anything wrong? CondaChangeEnv command from other plugin works.

Could you try setting `CONDA_EXE` environment variable to your anaconda envs path (`~/anaconda/envs` based on your comment) and leave the default value for `venvs_path`?
