### ISSUE TITLE
be able to select "base" in the pick_env function

### ISSUE THREAD

**Issue by zhengrc19** [AckslD/swenv.nvim#31]
Right now when I choose my Python environments the "base" environment doesn't show up, because for Conda envs `swenv.nvim` only looks in the `envs/` subfolder, while the "base" executable is in the `bin/` subfolder.

<img width="885" alt="image" src="https://github.com/AckslD/swenv.nvim/assets/13867494/a96b3632-00a5-4168-9008-54a432e45a01">

I have already written a piece of code to solve this (from setup), can I create a pull request to merge that code into the source?

**Comment by AckslD** [comment]
Hi @zhengrc19, yes feel free to open a PR :) I don't use conda so I appreciate the contribution.

**Comment by zhengrc19** [comment]
Hi @AckslD, just created the PR. I'm relatively new to contributing open source code so if there are any bad practices in my PR please point them out! Thanks!

**Comment by AckslD** [comment]
Great thanks!
