### ISSUE TITLE
Using Pyenv instead of Conda

### ISSUE THREAD

**Issue by Nicola-Bini** [AckslD/swenv.nvim#38]
Hi @AckslD,

Does this plugin requires conda? or is it also able to read local virtual environment created with (python -m venv .venv)?
I tried running it but it's returning the following error. My understanding is that the plugin reads the CONDA_EXE env variable to find environments. Is there a way to use pyenv instead?

> E5108: Error executing lua ...lunarvim/site/pack/lazy/opt/swenv.nvim/lua/swenv/api.lua:12: attempt to index local 'conda_exe_path' (a userdata value)
stack traceback:
        ...lunarvim/site/pack/lazy/opt/swenv.nvim/lua/swenv/api.lua:12: in function 'get_conda_base'
        ...lunarvim/site/pack/lazy/opt/swenv.nvim/lua/swenv/api.lua:55: in function 'get_venvs'
        ...lunarvim/site/pack/lazy/opt/swenv.nvim/lua/swenv/api.lua:81: in function 'pick_venv'
        [string ":lua"]:1: in main chunk

I loved the plugin!! Thank you so much for this!

**Comment by AckslD** [comment]
Hi @Nicola-Bini, could you try to update the plugin, looks like this is using an old version

**Comment by Microwave-WYB** [comment]
I also encountered this problem and I can confirm it the problem of LunarVim. It will install this repo instead: https://github.com/ChristianChiarulli/swenv.nvim

**Comment by Microwave-WYB** [comment]
If you are coming from the [post](https://betterprogramming.pub/lunarvim-as-a-python-ide-ca8f57ca9f3a) or the YouTube video, you are probably installing [this repo](https://github.com/ChristianChiarulli/swenv.nvim) instead. You can simply replace `"ChristianChiarulli/swenv.nvim"` with `"AckslD/swenv.nvim"`

**Comment by Nicola-Bini** [comment]
Thank you both!
you were right, I first installed the fork from Lunarvim, then replaced it with this repo. For some reason packer in Lunarvim is not set to update plugins on startup.
